### ISSUE TITLE
"Please specify name or/and region of Bus Slave" when building for Arty, Versa ECP5, or NeTV2

### ISSUE THREAD

**Issue by mglb** [litex-hub/linux-on-litex-vexriscv#101]
Output for Arty:
```
# ./make.py --board="Arty"

INFO:SoC:        __   _ __      _  __
INFO:SoC:       / /  (_) /____ | |/_/
INFO:SoC:      / /__/ / __/ -_)>  <
INFO:SoC:     /____/_/\__/\__/_/|_|
INFO:SoC:  Build your hardware, easily!
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Creating SoC... (2020-02-12 17:30:32)
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCBusHandler:Creating Bus Handler...
INFO:SoCBusHandler:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoCBusHandler:Adding reserved Bus Regions...
INFO:SoCBusHandler:Bus Handler created.
INFO:SoCCSRHandler:Creating CSR Handler...
INFO:SoCCSRHandler:8-bit CSR Bus, 16.0KiB Address Space, 2048B Paging (Up to 32 Locations).
INFO:SoCCSRHandler:Adding reserved CSRs...
INFO:SoCCSRHandler:ctrl CSR added at Location 0.
INFO:SoCCSRHandler:uart CSR added at Location 2.
INFO:SoCCSRHandler:timer0 CSR added at Location 3.
INFO:SoCCSRHandler:CSR Handler created.
INFO:SoCIRQHandler:Creating IRQ Handler...
INFO:SoCIRQHandler:IRQ Handler (up to 32 Locations).
INFO:SoCIRQHandler:Adding reserved IRQs...
INFO:SoCIRQHandler:IRQ Handler created.
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:Initial SoC:
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoC:32-bit wishbone Bus, 4.0GiB Address Space.
INFO:SoC:8-bit CSR Bus, 16.0KiB Address Space, 2048B Paging (Up to 32 Locations).
CSR Locations: (3)
- ctrl                : 0
- uart                : 2
- timer0              : 3
INFO:SoC:IRQ Handler (up to 32 Locations).
INFO:SoC:--------------------------------------------------------------------------------
INFO:SoCCSRHandler:ctrl CSR added at Location 0.
INFO:SoCBusHandler:io0 Region added Origin: 0x80000000, Size: 0x80000000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:cpu_bus0 added as Bus Master.
INFO:SoCBusHandler:cpu_bus1 added as Bus Master.
INFO:SoCCSRHandler:cpu CSR allocated at Location 1.
INFO:SoCIRQHandler:uart IRQ added at Location 0.
INFO:SoCIRQHandler:timer0 IRQ added at Location 1.
INFO:SoCBusHandler:rom Region added Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:rom added as Bus Slave.
INFO:SoC:RAM rom added Origin: 0x00000000, Size: 0x00008000, Mode: R, Cached: True Linker: False.
INFO:SoCBusHandler:sram Region added Origin: 0x10000000, Size: 0x00001000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:sram added as Bus Slave.
INFO:SoC:RAM sram added Origin: 0x10000000, Size: 0x00001000, Mode: RW, Cached: True Linker: False.
INFO:SoCCSRHandler:uart_phy CSR allocated at Location 4.
INFO:SoCCSRHandler:uart CSR added at Location 2.
INFO:SoCIRQHandler:uart IRQ added at Location 0.
INFO:SoCCSRHandler:timer0 CSR added at Location 3.
INFO:SoCIRQHandler:timer0 IRQ added at Location 1.
INFO:SoCBusHandler:csr Region added Origin: 0xf0000000, Size: 0x00010000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:csr added as Bus Slave.
INFO:SoCCSRHandler:bridge added as CSR Master.
INFO:SoCCSRHandler:ddrphy CSR allocated at Location 5.
INFO:SoCCSRHandler:sdram CSR allocated at Location 6.
INFO:SoCBusHandler:main_ram Region added Origin: 0xc0000000, Size: 0x10000000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:main_ram added as Bus Slave.
INFO:SoCCSRHandler:ethphy CSR allocated at Location 7.
INFO:SoCBusHandler:ethmac Region added Origin: 0xb0000000, Size: 0x00002000, Mode: RW, Cached: False Linker: False.
INFO:SoCBusHandler:ethmac added as Bus Slave.
INFO:SoCCSRHandler:ethmac CSR allocated at Location 8.
INFO:SoCIRQHandler:ethmac IRQ allocated at Location 2.
INFO:SoCBusHandler:emulator_ram Region added Origin: 0x20000000, Size: 0x00004000, Mode: RW, Cached: True Linker: False.
INFO:SoCBusHandler:emulator_ram added as Bus Slave.
INFO:SoCBusHandler:spiflash Region added Origin: 0xd0000000, Size: 0x01000000, Mode: RW, Cached: True Linker: False.
INFO:SoCCSRHandler:spiflash CSR allocated at Location 9.
INFO:SoCCSRHandler:leds CSR allocated at Location 10.
INFO:SoCCSRHandler:rgb_led_r0 CSR allocated at Location 11.
INFO:SoCCSRHandler:rgb_led_g0 CSR allocated at Location 12.
INFO:SoCCSRHandler:rgb_led_b0 CSR allocated at Location 13.
INFO:SoCCSRHandler:switches CSR allocated at Location 14.
INFO:SoCCSRHandler:spi CSR allocated at Location 15.
INFO:SoCCSRHandler:i2c0 CSR allocated at Location 16.
INFO:SoCCSRHandler:xadc CSR allocated at Location 17.
INFO:SoCCSRHandler:icap_bit CSR allocated at Location 18.
ERROR:SoCBusHandler:Please specify name or/and region of Bus Slave.
Traceback (most recent call last):
  File "./make.py", line 348, in <module>
    main()
  File "./make.py", line 335, in main
    builder.build()
  File "/home/travis/build/antmicro/linux-on-litex-vexriscv/src/litex/litex/soc/integration/builder.py", line 176, in build
    self.soc.finalize()
  File "/home/travis/build/antmicro/linux-on-litex-vexriscv/src/migen/migen/fhdl/module.py", line 157, in finalize
    self.do_finalize(*args, **kwargs)
  File "/home/travis/build/antmicro/linux-on-litex-vexriscv/src/litex/litex/soc/integration/soc_core.py", line 233, in do_finalize
    self.bus.add_slave(name=wb_name, slave=interface)
  File "/home/travis/build/antmicro/linux-on-litex-vexriscv/src/litex/litex/soc/integration/soc.py", line 315, in add_slave
    raise
RuntimeError: No active exception to reraise
```

Versa ECP5 and NeTV2 build gives the same error.

**Comment by enjoy-digital** [comment]
Thanks for reporting, fixed with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/9cb56e496aa094faf2d56b801eaedfcd92d4a014.
