### ISSUE TITLE
OSError: Unable to find images/Image memory content file.

### ISSUE THREAD

**Issue by Ankelih** [litex-hub/linux-on-litex-vexriscv#279]
Hello,

When I tried to run ./sim.py I get the following error.

> make: Leaving directory '/home/deniz/linux-on-litex-vexriscv/build/sim/software/bios'
> INFO:SoC:Initializing ROM rom with contents (Size: 0x5350).
> INFO:SoC:Auto-Resizing ROM rom from 0x10000 to 0x5350.
> Traceback (most recent call last):
>   File "./sim.py", line 177, in <module>
>     main()
>   File "./sim.py", line 161, in main
>     sdram_verbosity  = int(args.sdram_verbosity)
>   File "./sim.py", line 87, in __init__
>     ram_init = get_mem_data("images/boot.json", endianness="little", offset=0x40000000)
>   File "/home/deniz/litex/litex/soc/integration/common.py", line 50, in get_mem_data
>     raise OSError(f"Unable to find {filename} memory content file.")
> OSError: Unable to find images/Image memory content file.

How can I solve this problem?

**Comment by Ankelih** [comment]
I don't know whether it is correct or not but I downloaded prebuilt Linux/OpenSBI images and copied the files to images directory. After that I can successfully run sim.py
