### ISSUE TITLE
Fail to build 

### ISSUE THREAD

**Issue by wklam296** [litex-hub/linux-on-litex-vexriscv#328]
`build/icesugar_pro/icesugar_pro.dts:86.13-130.11: ERROR (phandle_references): /soc: Reference to non-existent node or label "intc0"`

`ERROR: Input tree has errors, aborting (use -f to force output)
Traceback (most recent call last):
  File "/linux-on-litex-vexriscv/./make.py", line 945, in <module>
    main()
  File "/linux-on-litex-vexriscv/./make.py", line 922, in main
    soc.compile_dts(board_name, args.fdtoverlays)
  File "/linux-on-litex-vexriscv/soc_linux.py", line 140, in compile_dts
    subprocess.check_call(
  File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dtc  -O dtb -o build/icesugar_pro/icesugar_pro.dtb build/icesugar_pro/icesugar_pro.dts' returned non-zero exit status 2.`

I don't know why this error occurs. Please help if possible thanks.

**Comment by OrkunAliOzkan** [comment]
Hi, if I had to assume, this error is likely similar to https://github.com/enjoy-digital/litex/issues/1615 and may be worth looking into. TLDR: intc0 label may be mislabelled by another stage/process, you gotta find out what aspect of the device that label represents and try determine what node with the valid label, from there just replace the label and it may work. Apologies if this isn't too much of help, but its worth looking into the url above!

**Comment by enjoy-digital** [comment]
Hi,

This seems to be fixed with the current LiteX/linux-on-litex-vexriscv tree.

I tested `./make.py --board=icesugar_pro` and the DTS now compiles correctly. The generated DTS contains the expected `intc0` interrupt-controller node, so the old `Reference to non-existent node or label "intc0"` error no longer reproduces.

Please update LiteX/LiteX-Boards/linux-on-litex-vexriscv and retry. Since this looks resolved, I think we can close this issue.
