### ISSUE TITLE
Failed to regenerate bitstreams with sipeed_tang_nano_9k 

### ISSUE THREAD

**Issue by EricZhang1412** [litex-hub/linux-on-litex-vexriscv#349]
chmod -x bios.bin
python3 -m litex.soc.software.crcfbigen bios.bin --little
python3 -m litex.soc.software.memusage bios.elf /home/ericzh/linux-on-litex-vexriscv/build/sipeed_tang_nano_9k/software/bios/../include/generated/regions.ld riscv64-unknown-elf

ROM usage: 31.69KiB     (49.51%)
RAM usage: 0.55KiB      (9.24%)

rm crt0.o
make: Leaving directory '/home/ericzh/linux-on-litex-vexriscv/build/sipeed_tang_nano_9k/software/bios'
Traceback (most recent call last):
  File "/home/ericzh/linux-on-litex-vexriscv/./make.py", line 999, in <module>
    main()
  File "/home/ericzh/linux-on-litex-vexriscv/./make.py", line 972, in main
    builder.build(run=args.build, build_name=board_name)
  File "/home/ericzh/litex/litex/soc/integration/builder.py", line 367, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/ericzh/litex/litex/soc/integration/soc.py", line 1332, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/ericzh/litex/litex/build/gowin/platform.py", line 43, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/ericzh/litex/litex/build/generic_toolchain.py", line 123, in build
    self.run_script(script)
  File "/home/ericzh/litex/litex/build/gowin/gowin.py", line 147, in run_script
    raise OSError(msg)
OSError: Unable to find Gowin toolchain, please:
- Add Gowin toolchain to your $PATH.

i can't find the PATH of my Gowin toolchain, even if i downloaded both win @ linux zip files on the internet. still, it does not work.

**Comment by peiceliu** [comment]
After you add the PATH of your Gowin toolchain to /etc/profile , you should source /etc/profile.Then i can work .

**Comment by pepijndevos** [comment]
Wait did you fit Linux on the Tang Nano 9K? It's not in the boards file and I'd imagine it's on the small side
