### ISSUE TITLE
README: Board names are misleading

### ISSUE THREAD

**Issue by xobs** [litex-hub/linux-on-litex-vexriscv#58]
The `Supported Boards` table has a list of board names, but these names are not valid for use with `--board`:

```sh
user@Pazuzu:~/Code/HaD/linux-on-litex-vexriscv$ python3 ./make.py --board ULX3S
Traceback (most recent call last):
  File "./make.py", line 254, in <module>
    main()
  File "./make.py", line 203, in main
    board = supported_boards[board_name]()
KeyError: 'ULX3S'
user@Pazuzu:~/Code/HaD/linux-on-litex-vexriscv$ python3 ./make.py --board "Versa ECP5"
Traceback (most recent call last):
  File "./make.py", line 254, in <module>
    main()
  File "./make.py", line 203, in main
    board = supported_boards[board_name]()
KeyError: 'Versa ECP5'
$
```

**Comment by enjoy-digital** [comment]
Thanks for the feedback, this is fixed with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/3943712e870f1ae80bcefd64339f71fdaf1df461.
