### ISSUE TITLE
KeyError: 'ethphy' on kcu105 build

### ISSUE THREAD

**Issue by mithro** [litex-hub/linux-on-litex-vexriscv#83]
https://travis-ci.com/litex-hub/linux-on-litex-vexriscv/jobs/277668500
```
make: Leaving directory '/home/travis/build/litex-hub/linux-on-litex-vexriscv/build/kcu105/software/bios'
Traceback (most recent call last):
  File "./json2dts.py", line 144, in <module>
    """.format(ethphy_csr_base=d["csr_bases"]["ethphy"],
KeyError: 'ethphy'
Traceback (most recent call last):
  File "./make.py", line 332, in <module>
    main()
  File "./make.py", line 321, in main
    soc.generate_dts(board_name)
  File "/home/travis/build/litex-hub/linux-on-litex-vexriscv/soc_linux.py", line 158, in generate_dts
    "./json2dts.py {} > {}".format(json, dts), shell=True)
  File "/home/travis/conda/envs/linux-on-litex-vexriscv/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './json2dts.py build/kcu105/csr.json > build/kcu105/kcu105.dts' returned non-zero exit status 1.
The command "./make.py --board="$BOARD"" exited with 1.
```

**Comment by enjoy-digital** [comment]
This has been fixed.
